/// Configuration for yield calculations.
#[derive(Debug, Clone, Copy, Default)]
pub struct ApyConfig {
    /// Annual percentage yield in basis points (e.g., 500 = 5%).
    pub rate_bps: u32,
}

impl ApyConfig {
    /// Create an ApyConfig from environment variables, defaulting to 0 bps.
    pub fn from_env() -> Self {
        let rate_bps = std::env::var("APY_RATE_BPS")
            .ok()
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(0);
        Self { rate_bps }
    }
}

/// Projects the virtual yield generated by a locked plan over time.
///
/// Uses simple interest formula:
///   accrued = principal * (rate_bps / 10000) * (elapsed_secs / seconds_per_year)
///
/// The yield_rate_bps is in basis points (e.g., 500 = 5% APY).
pub fn calculate_yield(amount: f64, yield_rate_bps: u32, elapsed_secs: u64) -> f64 {
    if yield_rate_bps == 0 || elapsed_secs == 0 {
        return 0.0;
    }

    let rate = yield_rate_bps as f64 / 10_000.0;
    let seconds_per_year = 365.25 * 24.0 * 3600.0;
    let time_years = elapsed_secs as f64 / seconds_per_year;

    amount * rate * time_years
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zero_yield_rate() {
        assert_eq!(calculate_yield(1000.0, 0, 86400), 0.0);
    }

    #[test]
    fn test_zero_elapsed() {
        assert_eq!(calculate_yield(1000.0, 500, 0), 0.0);
    }

    #[test]
    fn test_one_year_at_5_percent() {
        // 5% APY = 500 bps, 1 year = 31,536,000 seconds (approx)
        let one_year_secs = (365.25 * 24.0 * 3600.0) as u64;
        let yield_amount = calculate_yield(1000.0, 500, one_year_secs);
        // Should be ~50.0 (5% of 1000)
        assert!((yield_amount - 50.0).abs() < 0.01);
    }

    #[test]
    fn test_half_year() {
        // 10% APY = 1000 bps, half year should yield ~5% of principal
        let half_year_secs = (365.25 * 24.0 * 3600.0 / 2.0) as u64;
        let yield_amount = calculate_yield(1000.0, 1000, half_year_secs);
        // Should be ~50.0 (10% of 1000 for half year)
        assert!((yield_amount - 50.0).abs() < 0.01);
    }

    #[test]
    fn test_large_amount() {
        let one_year_secs = (365.25 * 24.0 * 3600.0) as u64;
        let yield_amount = calculate_yield(1_000_000.0, 200, one_year_secs);
        // 2% of 1,000,000 = 20,000
        assert!((yield_amount - 20_000.0).abs() < 1.0);
    }
}

use dashmap::DashMap;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

/// Dynamic liquidity pool or lending reserve rate data.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolRateInfo {
    pub pool_address: String,
    pub asset_symbol: String,
    pub supply_apy_bps: u32,
    pub borrow_apy_bps: u32,
    pub reserve_liquidity: u64,
    pub last_updated_secs: u64,
}

/// Dynamic market yield calculator supporting live pool queries.
#[derive(Clone)]
pub struct DynamicYieldCalculator {
    cache: Arc<DashMap<String, (u32, u64)>>,
    cache_ttl_secs: u64,
    rpc_endpoint: Option<String>,
}

impl DynamicYieldCalculator {
    pub fn new(rpc_endpoint: Option<String>, cache_ttl_secs: u64) -> Self {
        Self {
            cache: Arc::new(DashMap::new()),
            cache_ttl_secs,
            rpc_endpoint,
        }
    }

    /// Queries live pool or lending reserve yield, falling back to static APY if unavailable.
    pub async fn get_effective_rate_bps(
        &self,
        pool_or_token: &str,
        static_fallback_bps: u32,
    ) -> u32 {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        if let Some(entry) = self.cache.get(pool_or_token) {
            let (rate, ts) = *entry;
            if now.saturating_sub(ts) < self.cache_ttl_secs {
                return rate;
            }
        }

        if let Some(rate) = self.fetch_live_rate(pool_or_token).await {
            self.cache.insert(pool_or_token.to_string(), (rate, now));
            rate
        } else {
            static_fallback_bps
        }
    }

    async fn fetch_live_rate(&self, _pool_or_token: &str) -> Option<u32> {
        let _rpc = self.rpc_endpoint.as_deref()?;
        None
    }

    pub fn update_cached_rate(&self, pool_or_token: &str, rate_bps: u32) {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        self.cache
            .insert(pool_or_token.to_string(), (rate_bps, now));
    }
}
