name: Contracts CI

on:
  push:
    branches: ["main", "fix-ci", "master"]
    paths:
      - "contracts/**"
  pull_request:
    branches: ["main", "fix-ci", "master"]
    paths:
      - "contracts/**"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: contracts -> target

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all --release

      - name: Run tests
        run: cargo test --all --release --lib

      - name: Clippy
        run: cargo clippy --all --all-targets --all-features -- -D warnings